Feature/cnv 59
Conovel/environment pull request #1
Opened 2024-08-23 23:32 UTC by ryo-i

@azufb cc @technokuro
environment環境、cvn-59からdevelopへマージのプルリクになります。
レビューお願いいたしますmm

- .gitmodulesでサブモジュールとしてfrontend、backendを読み込む
- docker-compose.ymlでbackend、frontend、dbコンテナを操作
- builderディレクトリでbackend、frontend、dbコンテナのDockerfileでDockerイメージを設定

2024-08-24 03:04 UTC, technokuro reviewed
細かいですが一応

2024-08-24 03:04 UTC, technokuro commented on docker-compose.yml
> +  conobel-network:
typo
 conovel

2024-08-24 03:04 UTC, technokuro commented on docker-compose.yml
> +      - conobel-network
typo
 conovel

2024-08-24 03:04 UTC, technokuro commented on docker-compose.yml
> +      - conobel-network
typo
 conovel

2024-08-24 17:20 UTC, azufb requested changes
@ryo-i 
コメントしてます！！
ご確認お願いいたします！

2024-08-24 17:20 UTC, azufb commented on README.md
> +
@ryo-i 
Windowsだと、cloneしてくるときに改行コードが変換されてしまうようです。（私Windowsでして、これのエラーで引っかかって、起動できるようになるまで時間がかかってしまいました...）  
この自動変換を無効にするため、Windowsの場合は以下のコードを実行するよう追記して頂けるとより良いかと思いました！
自分が引っかかったポイントも「起動手順」の一部として記載すると、よりわかりやすいかと！

```
git config --global core.autocrlf input
```

新規でメンバー追加になることはないかとは思いますが、一応。

2024-08-25 09:09 UTC, ryo-i commented on docker-compose.yml
> +  conobel-network:
@technokuro 
こちら失礼しました、修正しましたmm
https://github.com/Conovel/environment/pull/1/commits/075ee71572e8ac4a334181ea860534e92d9047bb

2024-08-25 09:09 UTC, ryo-i commented on docker-compose.yml
> +      - conobel-network
https://github.com/Conovel/environment/pull/1/commits/075ee71572e8ac4a334181ea860534e92d9047bb

2024-08-25 09:09 UTC, ryo-i commented on docker-compose.yml
> +      - conobel-network
https://github.com/Conovel/environment/pull/1/commits/075ee71572e8ac4a334181ea860534e92d9047bb

2024-08-25 09:25 UTC, ryo-i commented on README.md
> +
@azufb 
Windows環境での動作確認ありがとうございます！ReadMeに追記しました
https://github.com/Conovel/environment/commit/ccb7131cb433c973d9566b0e742a955f239058b7

※こちらはenvironment環境だけの事象ではなく一般的な事象ですよね？その場合、frontend・backendリポジトリのReadMeにも同じ文章を記載しようと思います

2024-08-25 09:53 UTC, azufb commented on README.md
> +
@ryo-i  

> ※こちらはenvironment環境だけの事象ではなく一般的な事象ですよね？その場合、frontend・backendリポジトリのReadMeにも同じ文章を記載しようと思います

そうですね、environment環境だけではないです！！  
cloneしてくる時に発生する事象のようです。WSL使っても同じでした...😭
frontend・backendリポジトリにも記載お願いいたします！！

2024-08-25 10:17 UTC, ryo-i commented on README.md
> +
@azufb 
frontend・backendにも記載しました！
https://github.com/Conovel/frontend/commit/8c85b5e9e81b6d23c17858204663dbfb9d688016
https://github.com/Conovel/backend/commit/6b683ac8104771957be7c7eaa34c798d6d8e886c

2024-08-29 23:22 UTC, ryo-i commented on builder/backend/Dockerfile
> +    && rm -rf /var/lib/apt/lists/*
@technokuro @azufb 
PR補足：
ここの`RUN hogehoge`（ツール名）関係はDocker起動時にbackendで起こるエラー対策として追加インストールするツールです

2024-08-29 23:31 UTC, ryo-i commented
@azufb @technokuro 
PR補足を追記しました

2024-09-02 08:48 UTC, azufb approved these changes

2024-09-02 08:48 UTC, merged