[バック]投稿追加API（CNV-97）
Conovel/environment pull request #14
Opened 2024-12-08 09:32 UTC by ryo-i

### チケット

https://techno-kuro-novel.atlassian.net/browse/CNV-97

### 修正内容

#### スキーマ
エラーレスポンスの定義を追加しました

`ErrorResponse`スキーマに共通の定義（各APIのエラーレスポンスで参照）
```
{
  "error": {
    "code": "string",
    "message": "string"
  }
}
```

#### 409

sentences＞POST＞409は`ViewSentence`も一緒に返す
```
{
  "error": {
    "code": "string",
    "message": "string"
  },
  "main": {
    "sentence_id": 0,
    "sentence": "string",
    "sentence_user_id": 0,
    "sentence_user_name": "string",
    "profile_icon_image": "string",
    "evaluation_good_count": 0,
    "evaluation_stay_count": 0,
    "created_at": "2024-12-08T09:12:33.704Z",
    "updated_at": "2024-12-08T09:12:33.704Z"
  },
  "parent": {
    "sentence_id": 0,
    "sentence": "string",
    "sentence_user_id": 0,
    "sentence_user_name": "string",
    "profile_icon_image": "string",
    "evaluation_good_count": 0,
    "evaluation_stay_count": 0,
    "created_at": "2024-12-08T09:12:33.704Z",
    "updated_at": "2024-12-08T09:12:33.704Z"
  },
  "parallels": [
    {
      "sentence_id": 0,
      "sentence": "string",
      "sentence_user_id": 0,
      "sentence_user_name": "string",
      "profile_icon_image": "string",
      "evaluation_good_count": 0,
      "evaluation_stay_count": 0,
      "created_at": "2024-12-08T09:12:33.704Z",
      "updated_at": "2024-12-08T09:12:33.704Z"
    }
  ],
  "children": [
    {
      "sentence_id": 0,
      "sentence": "string",
      "sentence_user_id": 0,
      "sentence_user_name": "string",
      "profile_icon_image": "string",
      "evaluation_good_count": 0,
      "evaluation_stay_count": 0,
      "created_at": "2024-12-08T09:12:33.704Z",
      "updated_at": "2024-12-08T09:12:33.704Z"
    }
  ]
}
```
#### 422

論理エラーを追加

ステータスコードは422のみで、メッセージを出し分ける想定です。
https://developer.mozilla.org/ja/docs/Web/HTTP/Status/422
https://developer.mozilla.org/ja/docs/Web/HTTP/Status#クライアントエラーレスポンス

メッセージ例：
https://techno-kuro-novel.atlassian.net/wiki/spaces/Conovel/pages/3145744
- 1 回の投稿で、100 文字 1 文のみ投稿できる。 
  - 「投稿文字数の上限を超えています。修正後に再投稿をお願いします。」
- 自分の投稿の直後は自分で投稿できない。
  - 「自分自身の投稿に連続で投稿を追加することはできません。」

2024-12-09 11:14 UTC, azufb requested changes
@ryo-i
CC： @technokuro 
気になるところを見つけたのでコメントしてます！！
ご回答頂けると助かります！

---------
また、PRのタイトルなのですが、今回エラーメッセージの対応をして頂いていて、投稿追加APIを実装したわけではない認識です。
（↑そもそもこの認識が違ってたらごめんなさい...！）
ですので、このPRのタイトルにするのはちょっと違和感があるかなぁ～と思いました！
レビューコメントへの回答に加えて、PRのタイトル修正もお願いできると助かります！

PRタイトルは、そのPRで「何をしたのか」が簡単にわかるようなタイトルにして頂けると助かるかなと思います！基本的には、チケットタイトルをそのままPRタイトルにするのが手っ取り早いとは思いますが、今回については、当てはまらないケースだったかもと思いました！

2024-12-09 11:14 UTC, azufb commented on conovel-openapi.yml
> +                $ref: "#/components/schemas/ErrorResponse"
@ryo-i @technokuro 
こちら「ユーザーが見つからない」となってますが、他の小説一覧取得とかと同様に、リストの取得失敗ではないんですね？？
こちらはリストの取得失敗のエラーは不要になったんでしたっけ？？
（チェック遅くなってすいません！！）

2024-12-09 11:14 UTC, azufb commented on conovel-openapi.yml
> +                $ref: "#/components/schemas/ErrorResponse"
@ryo-i @technokuro 
こちらも同様に気になりました！
チェック遅くなってすいません！

2024-12-09 22:23 UTC, ryo-i reviewed
また、PRのタイトルなのですが、今回エラーメッセージの対応をして頂いていて、投稿追加APIを実装したわけではない認識です。
（↑そもそもこの認識が違ってたらごめんなさい...！）
ですので、このPRのタイトルにするのはちょっと違和感があるかなぁ～と思いました！
レビューコメントへの回答に加えて、PRのタイトル修正もお願いできると助かります！
@azufb 
ご確認ありがとうございます！
GET系エラーについては、400「失敗しました」を追加すべきか（404「見つからない」は残したまま）と感じまして、@technokuroさんに質問コメントを書きましたmm

> また、PRのタイトルなのですが、今回エラーメッセージの対応をして頂いていて、投稿追加APIを実装したわけではない認識です。

今回の修正の意図を伝え漏れており、すみません。
今回のエラーメッセージの修正意図のメインは「投稿追加APIを実装」の一環と捉えておりました。
投稿追加APIのエラー「文字数超過」「同一人物が連続投稿できない」などのエラーケースを追加すること。
（投稿追加API以外のエラーメッセージについてはErrorResponseスキーマが共通なためにおまけで反映した認識）

※また、昨日作成した下記の質問チケットも投稿追加APIのエラーメッセージ仕様の確定の目的があります。
https://techno-kuro-novel.atlassian.net/browse/CNV-143
（投稿編集機能がない場合、409「親投稿が編集されたため、投稿を保留」の仕様は不要になる認識）

---

> レビューコメントへの回答に加えて、PRのタイトル修正もお願いできると助かります！
> PRタイトルは、そのPRで「何をしたのか」が簡単にわかるようなタイトルにして頂けると助かるかなと思います！

承知しました！PRタイトルを下記に修正してみました。
- As Is：[バック]投稿追加API（CNV-97）
- To Be：[バック]投稿追加API（CNV-97）& 各エラーメッセージ定義

※メインの内容は投稿追加APIだが、それ以外のAPIのエラーメッセージの修正も含むニュアンス

2024-12-09 22:23 UTC, ryo-i commented on conovel-openapi.yml
> +                $ref: "#/components/schemas/ErrorResponse"
@azufb 
GET系の処理で「xxxが見つからない」という事象は起こり得ると想定できたのであらかじめ404 「見つからない」というエラーレスポンスを定義しました。

他のAPIは具体的な事象がまだ想定しきれていないが、エラー自体は起こり得るだとうということで400  「失敗しました」にしている感じでした

@technokuro 
GET系のエラーに「見つからない」以外のエラーも起こり得そうな場合は、400「失敗しました」のエラーも追加しておこうと思うのですが、いかがでしょう（404「見つからない」は残したままで）

2024-12-09 22:23 UTC, ryo-i commented on conovel-openapi.yml
> +                $ref: "#/components/schemas/ErrorResponse"
@azufb cc @technokuro 
上記と同様（その他のGET系エラーも）

2024-12-12 12:08 UTC, technokuro commented on conovel-openapi.yml
> +                $ref: "#/components/schemas/ErrorResponse"
YAGNI　で、今想定していないことは、作らなくていいです。
結果、yml　にないまま、つくってしまっても良いルールなら楽ですけどね。

この辺はPJのルールですが、私としては予実が乖離しても差し支えありません。

ちなみに {x}が見つかりません　とかのプレースホルダにしてしまえばいいと思いますけどね

2024-12-12 12:08 UTC, technokuro commented on conovel-openapi.yml
> +                $ref: "#/components/schemas/ErrorResponse"
👆同様

2024-12-12 12:21 UTC, azufb approved these changes

2024-12-12 12:21 UTC, technokuro approved these changes

2024-12-12 12:22 UTC, merged