Rails環境：MySQL読み込み動作検証
Conovel/environment pull request #4
Opened 2024-10-09 22:26 UTC by ryo-i

## JIRAチケットURL
https://techno-kuro-novel.atlassian.net/browse/CNV-65

※[[バック]後続・パラレルv取得API](https://techno-kuro-novel.atlassian.net/browse/CNV-96)のサブタスクです

----

## 実装内容
- `README.md`：今回の修正で今後の開発時にも必要と感じた手順を追記
- `conovel-openapi.yml`：API定義の変更
  - As Is：openapi-generatorのドキュメントにあった`pets`の内容
  - To Be：小説閲覧画面で表示する投稿（ER図の`sentences`テーブル）の内容に変更
  - ただし、本ブランチではデータはデータベースとの連携の動作確認がメインの目的のため最低限にしている
  - カラム：`sentence_id`、`sentence`、`created_at`、`updated_at`のみ
- `docker-compose.yml`：`volumes`に`./backend:/app`を追加（バックエンド環境を永続化させるため）
- `openapigen/index.html`：`conovel-openapi.yml`の修正後にビルドしたAPIドキュメント
- `backend`：サブモジュール（コミットID更新）
- `frontend`：サブモジュール（コミットID更新）
----

## テスト
- APIドキュメントの更新：前回の`pets`が`sentences`の内容に更新されている
![スクリーンショット 2024-10-10 7 19 34](https://github.com/user-attachments/assets/216066db-5889-4f51-bbaa-b8f8ad86abfe)

----

## 結合テスト・受入テストに持ち越すテスト項目（必ず1つ以上作成）

- 本ブランチはCNV-96のサブブランチのため、developではなくCNV-96のブランチにマージをいたします
- 本ブランチは`frontend`リポジトリ、`backend`リポジトリをサブモジュールとして読み込んでおり、それらのコミットIDの更新も本ブランチのコミットとしてプッシュします
- そのため、`frontend`リポジトリ、`backend`リポジトリのPRのマージ後に本PRのマージをお願いいたしますmm

2024-10-10 11:50 UTC, technokuro commented on conovel-openapi.yml
> +                type: object
@ryo-i 

`components/schemas/Sentence` の名付けコンポーネントスキーマを付けるといいです。
理由は、
https://github.com/Conovel/frontend/pull/11/files#diff-f73ea09db8d4d348c88e2c5e9413955b679d52988cb11e57fa7235d695039ec4R29
👆のように、変な名前がモデル名についてしまうためです。
‘Pet` は、スキーマに名づけをしていたため、モデル名に名前が適用されていました。

2024-10-10 22:40 UTC, ryo-i commented on conovel-openapi.yml
> +                type: object
@technokuro 
ありがとうございます！schemaを読み込む形に修正しました。ご確認お願いしますmm
`openapigen/index.html`のドキュメントを再ビルドしてみたところ、この中にあった長い項目名も短くなりました！
https://github.com/Conovel/environment/pull/4/commits/ce50b9791dc731e583fff2e6a4b6341ec90f6e6a

ちょっと悩んでいるのが、schemaの名前を単数形の`Sentence`にするか、複数形の`Sentences`にするか。
メインの投稿を表示する意味では単数の`Sentence`な気がしました。
ただ、画面では上下に親投稿や子投稿が小さく表示されていて、レスポンスも最終的にその親子投稿のデータを含んだ形になるため、その意味では複数の`Sentences`とも言えるのかなと
（投稿が並列ではなくメインとサブの関係ではあるのを単数と捉えるか複数で捉えるか悩ましい、、）

こちらが確定したらfrontend、backendの方にも反映していきたく思いますmm

2024-10-11 06:55 UTC, technokuro commented on conovel-openapi.yml
> +                type: object
@ryo-i 
`pet`　と　`pets`　　の関係と同じように作ればいいのかな、と思いました。
あくまで定義なので、 paths の中で使うかどうかは一旦考えず（多分使うし）作ってしまいましょう。

2024-10-12 03:16 UTC, ryo-i commented on conovel-openapi.yml
> +                type: object
@technokuro 
ありがとうございます！`pets`を参考に`sentences`を作りました
https://github.com/Conovel/environment/pull/4/commits/d04c928e80497fd5e813737bb7ff905814b6c0cf
- `sentences`の中で`schema`で`sentence`を読み込んでいる
- ただ、`sentences`を`/sentences/{sentence_id}`で読み込むと配列になる（閲覧画面では`sentence_id`のメイン投稿のみ取得のため配列にする必要はなさそう）ため、そちらでは`sentence`を読み込む形にしています
- `sentences`は複数件の`sentence`を配列で送る形ですが、`sentence`は今後、`main`の他に`parents`や`children`などの投稿も加える予定のため、`sentences`の中にそれらの情報が必要かについては考慮が必要かもしれません

2024-10-12 04:06 UTC, ryo-i commented on conovel-openapi.yml
> +                type: object
@technokuro 
あとから思ったのですが、schemaのsentenceにmain:を含ませないほうが汎用性が高いのかも？
そのほうがsentencesの配列もmainを含めないほうが汎用性が高まりそうな気がしました。
もう少し検討してみるので、修正したらまた連絡しますmm

2024-10-13 02:53 UTC, ryo-i commented on conovel-openapi.yml
> +                type: object
@technokuro cc @azufb 
修正しました！ご確認お願いしますmm
https://github.com/Conovel/environment/pull/4/commits/2d4fb61c5063d5705f83815cbd0fb2056408c651

**修正内容**
- `schemas`の`Sentence`から`main:`を削除
- `schemas`に`ViewSentence`を追加
- `ViewSentence`の中で`main:`の下で`Sentence`を読み込む
- `responses`の`200`よ読み込む`schema`を`Sentence`から`ViewSentence`に変更

**ドキュメント再ビルド**
- `openapigen/index.html`ドキュメントを再ビルド
- `get /sentences/{sentence_id}`の形は変わらず
- `Example data`のjsonの事例も変わらず
![スクリーンショット 2024-10-13 11 41 13](https://github.com/user-attachments/assets/596287df-32e6-4c4e-af73-cadcbd41be6f)

**今後の想定（別チケット）**
- `Sentence`の中に他に小説閲覧画面に必要な必要なプロパティを追加していく
- `ViewSentence`にメイン投稿`main`以外のプロパティ（親投稿`parent`、親パラレル投稿`parentParallel`、子投稿`children`など）も追加する予定
- 親パラレル投稿、子投稿は複数になると思うので、配列型の`Sentences`スキーマを読み込む予定

2024-10-13 22:20 UTC, technokuro commented on conovel-openapi.yml
> +  title: Sentences API
@ryo-i 
今回はいったんこれでいいかなと思いましたが、一応認識確認
今後 `sentences` 以外の 例えば `evaluations` などの情報も `paths` 配下に並びます。
なので、 `title` は正直 `conovel` でいいと思います。
機能ごとに yaml ファイルができるわけじゃないです

2024-10-13 22:20 UTC, technokuro commented on conovel-openapi.yml
> +    ViewSentence:
@ryo-i 
表示するために必要となる要素　という意味で名前はこの辺がいいかなと思いました

2024-10-13 22:20 UTC, technokuro commented on conovel-openapi.yml
> +        main:
@ryo-i 
`main` が　現在注目している１つの `sentence` という意味なら `current` かなと思いました。
このほかに、親（直親の1要素、単体）　や　親の兄弟（親階層にあるパラレル要素、配列）、後続の要素列（後続のパラレル要素すべて、配列）なども、表現されると思っています。

一回👆でディスカッションさせてください（Approveはそのあとで）

2024-10-13 22:51 UTC, ryo-i commented on conovel-openapi.yml
> +  title: Sentences API
@technokuro 
> 機能ごとに yaml ファイルができるわけじゃないです
確かに、、おっしゃる通りに感じましたので、`title`は`Conovel API`に変更いたしますmm

2024-10-13 22:52 UTC, ryo-i commented on conovel-openapi.yml
> +    ViewSentence:
@technokuro 
スキーム名は`ViewSentence`で問題ないということですよね？
ありがとうございます！

2024-10-13 22:58 UTC, ryo-i commented on conovel-openapi.yml
> +        main:
@technokuro 
> main が　現在注目している１つの sentence という意味

はい、その認識であっています！
小説閲覧画面で言うと天地のセンターにある一番大きく表示されるメインの投稿を意味しています。
`main`より`current`の方が誤解がない表現になりそうであれば、`current`に変更しようと思います。

> このほかに、親（直親の1要素、単体）　や　親の兄弟（親階層にあるパラレル要素、配列）、後続の要素列（後続のパラレル要素すべて、配列）なども、表現される

その認識もあっています。レスポンスのjsonとしては下記のような並列な形になることを想定しています
```javascript
{
  main: { /* メインの投稿の内容 */ },
  parent: { /* 親投稿の内容 */ },
  parentParallel: [ // 単語2つはキャメルケース or ケバブケース？（検討中）
    { /* 親のパラレル投稿 */},
    { /* 親のパラレル投稿 */},
    { /* 親のパラレル投稿 */},
  ],
  chidlren: [
    { /* 子投稿 */},
    { /* 子投稿 */},
    { /* 子投稿 */},
  ],
}
```
- 配列のところは`Sentences`スキーマの想定
- `main`は`current`の方が良さそうであれば`carrent`に変更予定

2024-10-13 23:53 UTC, technokuro commented on conovel-openapi.yml
> +        main:
@ryo-i 
一度のディスカッションで `main` でも `current` でも微々たる差だなと思いました
ので、Approve♪

2024-10-13 23:53 UTC, technokuro approved these changes

2024-10-14 07:30 UTC, ryo-i reviewed
@technokuro @azufb @Yuya757 
- openapiで生成されるファイルの説明のうち、`api.ts`の説明が抜けていたので追加しました
- また、説明するファイルの順番をアルファベット順にした方がVSCodeのExplorerの表示と一致してわかりやすいと思ったので順序を入れ替えました

2024-10-14 23:11 UTC, technokuro requested changes

2024-10-14 23:11 UTC, technokuro commented on conovel-openapi.yml
> -      operationId: listPets
@ryo-i 
今気づきました💦
operationId をつけましょうか。
ここに反映されます
https://github.com/Conovel/frontend/pull/11/files#diff-f73ea09db8d4d348c88e2c5e9413955b679d52988cb11e57fa7235d695039ec4R84

2024-10-15 10:26 UTC, ryo-i reviewed
@technokuro 
修正しました！ご確認お願いいたしますmm

2024-10-15 10:26 UTC, ryo-i commented on conovel-openapi.yml
> -      operationId: listPets
@technokuro 
`operationId`を追加しました！ご確認お願いいたしますmm
https://github.com/Conovel/environment/pull/4/commits/323bd8677b4ad8477d8c9eff6f9dc8dd81b60e12

frontendにも修正を反映しました！メソッド名などが短くなりました（API通信の動作は影響ありませんでした）
https://github.com/Conovel/frontend/pull/11/commits/a99226ec4fc49d9611951020b29f5a0103dace6b

backendの方も何か変化があるか念の為、再ビルドしてみましたが、`FILES`という設定が更新されたのみで変化はありませんでした（`FILES`は本体に移植してないため、本体のRails環境には影響ありません）
https://github.com/Conovel/backend/pull/6/commits/dc4e95dbbb54fc3c4c6bf41587485448bc0e61ac

2024-10-15 22:17 UTC, technokuro approved these changes
@ryo-i 
ありがとうございました！

2024-10-16 09:50 UTC, azufb approved these changes

2024-10-16 09:52 UTC, merged